# Generated by Django 4.2.27 on 2025-12-28 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaging',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagings', to='users.parent'),
        ),
        migrations.AddField(
            model_name='messaging',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagings', to='users.student'),
        ),
        migrations.AddField(
            model_name='messaging',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagings', to='users.staff'),
        ),
        migrations.AddField(
            model_name='message',
            name='messaging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.messaging'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communications.announcement'),
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communications.announcement'),
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_announcements', to='schools.school'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='messaging',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', True)), fields=('teacher', 'parent'), name='unique_messaging_teacher_parent'),
        ),
        migrations.AddConstraint(
            model_name='messaging',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('teacher', 'student'), name='unique_messaging_teacher_student'),
        ),
        migrations.AddIndex(
            model_name='announcementrecipient',
            index=models.Index(fields=['user', 'is_read'], name='communicati_user_id_23e9da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementrecipient',
            unique_together={('announcement', 'user')},
        ),
    ]
