# Generated by Django 4.2.23 on 2025-10-18 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('schools', '0001_initial'),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaging',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagings', to='users.parent'),
        ),
        migrations.AddField(
            model_name='messaging',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagings', to='users.staff'),
        ),
        migrations.AddField(
            model_name='message',
            name='messaging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.messaging'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='schools.school'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_announcements', to='users.staff'),
        ),
        migrations.AddConstraint(
            model_name='messaging',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('parent', 'teacher'), name='unique_active_messaging_parent_teacher'),
        ),
    ]
