# Generated by Django 4.2.27 on 2026-07-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_homeworksubmission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementrecipient',
            name='requires_submission',
        ),
        migrations.AddField(
            model_name='announcement',
            name='requires_submission',
            field=models.BooleanField(default=False, help_text='Coché si ce devoir nécessite un rendu de la part des élèves.'),
        ),
    ]
