# Generated by Django 4.2.23 on 2025-12-03 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('communications', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='messaging',
            options={'ordering': ['-last_message_date']},
        ),
        migrations.RemoveConstraint(
            model_name='messaging',
            name='unique_active_messaging_parent_teacher',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_type',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messaging',
            name='last_message_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messaging',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagings', to='users.student'),
        ),
        migrations.AlterField(
            model_name='messaging',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagings', to='users.parent'),
        ),
        migrations.AddConstraint(
            model_name='messaging',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', True)), fields=('teacher', 'parent'), name='unique_messaging_teacher_parent'),
        ),
        migrations.AddConstraint(
            model_name='messaging',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('teacher', 'student'), name='unique_messaging_teacher_student'),
        ),
    ]
