# Generated by Django 4.2.23 on 2025-12-05 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0002_initial'),
        ('communications', '0004_alter_message_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='announcements_files/%Y/%m/')),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo'), ('DOCUMENT', 'Document')], default='DOCUMENT', max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='type',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='video',
        ),
        migrations.AddField(
            model_name='announcement',
            name='announcement_type',
            field=models.CharField(choices=[('HOMEWORK', 'Devoir'), ('TEST', 'Contrôle'), ('COURSE', 'Cours'), ('MESSAGE', 'Message Global')], default='MESSAGE', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_display',
            field=models.CharField(blank=True, help_text='Résumé des destinataires pour affichage', max_length=255),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_announcements', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
        migrations.AddField(
            model_name='attachment',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communications.announcement'),
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communications.announcement'),
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='announcementrecipient',
            index=models.Index(fields=['user', 'is_read'], name='communicati_user_id_23e9da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementrecipient',
            unique_together={('announcement', 'user')},
        ),
    ]
