# Generated by Django 4.2.23 on 2025-12-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_announcementrecipient_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
