# Generated by Django 4.2.23 on 2025-10-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], default=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_inactive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyScheduleInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Semaine 1', max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
