# Generated by Django 4.2.23 on 2025-08-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_inactive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_week', models.IntegerField(choices=[(1, 'Week Cycle 1'), (2, 'Week Cycle 2'), (3, 'Week Cycle 3'), (4, 'Week Cycle 4')], default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
