# Generated by Django 4.2.27 on 2025-12-28 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyscheduletemplate',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_template_years', to='schools.year'),
        ),
        migrations.AddField(
            model_name='scheduledcourse',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_courses_classroom', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='scheduledcourse',
            name='course_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_instances', to='scheduling.coursetemplate'),
        ),
    ]
