# Generated by Django 4.2.23 on 2025-08-31 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('schools', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplanning',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plannings', to='schools.year'),
        ),
        migrations.AddField(
            model_name='course',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='course',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='classes.class'),
        ),
    ]
