# Generated by Django 4.2.23 on 2025-09-06 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyscheduletemplate',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_template_annee', to='schools.year'),
        ),
        migrations.AddField(
            model_name='weeklyscheduleinstance',
            name='schedule_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_template', to='scheduling.weeklyscheduletemplate'),
        ),
        migrations.AddField(
            model_name='course',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_classroom', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='course',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_student_class', to='classes.class'),
        ),
    ]
