# Generated by Django 4.2.23 on 2025-09-07 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('scheduling', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_teacher_subject', to='subjects.teachersubject'),
        ),
        migrations.AddField(
            model_name='course',
            name='weekly_planning_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_weekly_planning_template', to='scheduling.weeklyscheduletemplate'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('day_of_week', 'start_time', 'end_time', 'teacher_subject', 'weekly_planning_template'), name='unique_teacher_course_per_week'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('day_of_week', 'start_time', 'end_time', 'student_class', 'weekly_planning_template'), name='unique_class_course_per_week'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('day_of_week', 'start_time', 'end_time', 'classroom', 'weekly_planning_template'), name='unique_classroom_course_per_week'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('day_of_week', 'start_time', 'end_time', 'teacher_subject', 'student_class', 'classroom', 'weekly_planning_template'), name='unique_classroom_course_per_week_all'),
        ),
    ]
