# Generated by Django 4.2.27 on 2025-12-28 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0004_initial'),
        ('subjects', '0001_initial'),
        ('schools', '0001_initial'),
        ('scheduling', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledcourse',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledcourse',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_courses_class', to='classes.class'),
        ),
        migrations.AddField(
            model_name='scheduledcourse',
            name='teacher_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_courses_teacher', to='subjects.teachersubject'),
        ),
        migrations.AddField(
            model_name='scheduledcourse',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_courses_year', to='schools.year'),
        ),
        migrations.AddField(
            model_name='coursetemplate',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_templates', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='coursetemplate',
            name='teacher_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_templates', to='subjects.teachersubject'),
        ),
        migrations.AddField(
            model_name='coursetemplate',
            name='weekly_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_templates', to='scheduling.weeklyscheduletemplate'),
        ),
        migrations.AddConstraint(
            model_name='coursetemplate',
            constraint=models.UniqueConstraint(fields=('day_of_week', 'start_time', 'end_time', 'teacher_subject', 'weekly_template'), name='unique_teacher_course_per_template'),
        ),
        migrations.AddConstraint(
            model_name='coursetemplate',
            constraint=models.UniqueConstraint(fields=('day_of_week', 'start_time', 'end_time', 'classroom', 'weekly_template'), name='unique_classroom_course_per_template'),
        ),
    ]
