# Generated by Django 4.2.23 on 2025-08-31 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0002_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='subjects.teachersubject'),
        ),
        migrations.AddField(
            model_name='course',
            name='weekly_planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='scheduling.weeklyplanning'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('day', 'start_time', 'end_time', 'teacher_subject', 'weekly_planning'), name='unique_teacher_course_per_week'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('day', 'start_time', 'end_time', 'student_class', 'weekly_planning'), name='unique_class_course_per_week'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('day', 'start_time', 'end_time', 'classroom', 'weekly_planning'), name='unique_classroom_course_per_week'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('day', 'start_time', 'end_time', 'teacher_subject', 'student_class', 'classroom', 'weekly_planning'), name='unique_classroom_course_per_week_all'),
        ),
    ]
