# Generated by Django 4.2.23 on 2025-11-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyscheduletemplate',
            unique_together=set(),
        ),
    ]
