# Generated by Django 4.2.23 on 2025-11-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_weeklyscheduletemplate_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledcourse',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Actif'), ('CANCELLED', 'Cours annulé'), ('TEACHER_ABSENT', 'Professeur absent')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
