# Generated by Django 4.2.27 on 2026-05-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='national_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
