# Generated by Django 4.2.23 on 2025-08-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='email.manquant', max_length=254, unique=True),
        ),
    ]
