# Generated by Django 4.2.23 on 2025-09-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='parent_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='email_a_remplir@gmail.com', max_length=254, null=True, unique=True),
        ),
    ]
