# Generated by Django 4.2.27 on 2026-07-23 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_national_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_text', models.TextField(verbose_name='Adresse complète')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ville')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='users.student')),
            ],
        ),
    ]
