# Generated by Django 4.2.23 on 2025-10-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassStudentYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delegate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClassTeacherYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_main_teacher', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('6E', '6e'), ('5E', '5e'), ('4E', '4e'), ('3E', '3e'), ('2ND', 'Seconde'), ('1ER', 'Première'), ('T', 'Terminale'), ('BTS1', 'Bts1'), ('BTS2', 'Bts2')], default='6E', max_length=255)),
                ('term_type', models.CharField(choices=[('TRIMESTRE', 'Trimestre'), ('SEMESTRE', 'Semestre')], default='TRIMESTRE', max_length=10)),
            ],
        ),
    ]
