# Generated by Django 4.2.23 on 2025-08-31 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0003_initial'),
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classstudentyear',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_years', to='users.student'),
        ),
        migrations.AddField(
            model_name='classstudentyear',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_years', to='classes.class'),
        ),
        migrations.AddField(
            model_name='classstudentyear',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_classes', to='schools.year'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='schools.school'),
        ),
        migrations.AddField(
            model_name='class',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.level'),
        ),
        migrations.AlterUniqueTogether(
            name='classteacheryear',
            unique_together={('student_class', 'teacher', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='classstudentyear',
            unique_together={('student_class', 'student', 'year')},
        ),
    ]
