# Generated by Django 4.2.23 on 2025-09-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='term_type',
            field=models.CharField(choices=[('TRIMESTRE', 'Trimestre'), ('SEMESTRE', 'Semestre')], default='TRIMESTRE', max_length=10),
        ),
    ]
