# Generated by Django 4.2.23 on 2025-10-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(choices=[('6E', '6e'), ('5E', '5e'), ('4E', '4e'), ('3E', '3e'), ('2ND', 'Seconde'), ('1ER', 'Première'), ('T', 'Terminale'), ('BTS1', 'Bts1'), ('BTS2', 'Bts2')], default='6E', max_length=255),
        ),
    ]
