# Generated by Django 4.2.23 on 2025-09-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='type',
        ),
    ]
