# Generated by Django 4.2.27 on 2026-07-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(choices=[('6E', '6e'), ('5E', '5e'), ('4E', '4e'), ('3E', '3e'), ('2ND', 'Seconde'), ('1ER', 'Première'), ('T', 'Terminale'), ('BTS1', 'Bts1'), ('BTS2', 'Bts2'), ('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('1A', '1er année'), ('2A', '2e année'), ('3A', '3e année'), ('4A', '4e année'), ('5A', '5e année'), ('6A', '6e année'), ('7A', '7e année'), ('8A', '8e année'), ('9A', '9e année'), ('10A', '10e année')], default='6E', max_length=255),
        ),
        migrations.AlterField(
            model_name='level',
            name='term_type',
            field=models.CharField(choices=[('TRIMESTRE', 'Trimestre'), ('SEMESTRE', 'Semestre'), ('UNIQUE', 'Unique')], default='TRIMESTRE', max_length=10),
        ),
    ]
