# Generated by Django 4.2.23 on 2025-09-05 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_level_term_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_level', to='classes.level'),
        ),
    ]
