# Generated by Django 4.2.23 on 2025-10-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='Aucune apréciation.')),
                ('is_global', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_value', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('coefficient', models.FloatField(default=1.0)),
                ('is_absent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_type', models.CharField(choices=[('AB', 'Assez Bien'), ('B', 'Bien'), ('TB', 'Très Bien')], max_length=2)),
            ],
        ),
    ]
