# Generated by Django 4.2.27 on 2025-12-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('is_global', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('coefficient', models.FloatField(default=1.0)),
                ('max_grade', models.FloatField(default=20.0)),
                ('is_main_grade', models.BooleanField(default=False, verbose_name='Est une note principale')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_value', models.FloatField(blank=True, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_type', models.CharField(choices=[('AB', 'Assez Bien'), ('B', 'Bien'), ('TB', 'Très Bien'), ('EX', 'Excellent'), ('FE', 'Félicitations'), ('EN', 'Encouragements'), ('AV', 'Avertissement Travail'), ('AC', 'Avertissement Conduite')], max_length=2)),
            ],
        ),
    ]
