# Generated by Django 4.2.27 on 2025-12-28 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0004_initial'),
        ('users', '0001_initial'),
        ('subjects', '0001_initial'),
        ('grades', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='users.student'),
        ),
        migrations.AddField(
            model_name='mention',
            name='term_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='schools.termyearlevel'),
        ),
        migrations.AddField(
            model_name='grade',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='grades.evaluation'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='users.student'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='classes.class'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='teacher_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='subjects.teachersubject'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='term_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='schools.termyearlevel'),
        ),
        migrations.AddField(
            model_name='appreciation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations', to='users.student'),
        ),
        migrations.AddField(
            model_name='appreciation',
            name='teacher_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appreciations', to='subjects.teachersubject'),
        ),
        migrations.AddField(
            model_name='appreciation',
            name='term_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations', to='schools.termyearlevel'),
        ),
        migrations.AlterUniqueTogether(
            name='mention',
            unique_together={('student', 'term_year')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('evaluation', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='appreciation',
            unique_together={('student', 'term_year', 'teacher_subject')},
        ),
    ]
