# Generated by Django 4.2.23 on 2025-08-31 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('scheduling', '0003_initial'),
        ('users', '0001_initial'),
        ('grades', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='users.student'),
        ),
        migrations.AddField(
            model_name='mention',
            name='term_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='schools.termyear'),
        ),
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='scheduling.course'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='users.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='term_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='schools.termyear'),
        ),
        migrations.AddField(
            model_name='appreciation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations', to='users.student'),
        ),
        migrations.AddField(
            model_name='appreciation',
            name='teacher_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appreciations', to='subjects.teachersubject'),
        ),
        migrations.AddField(
            model_name='appreciation',
            name='term_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations', to='schools.termyear'),
        ),
        migrations.AlterUniqueTogether(
            name='mention',
            unique_together={('student', 'term_year')},
        ),
    ]
