# Generated by Django 4.2.23 on 2025-11-07 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_initial'),
        ('users', '0001_initial'),
        ('classes', '0004_initial'),
        ('subjects', '0002_initial'),
        ('grades', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='users.student'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('coefficient', models.FloatField(default=1.0)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='classes.class')),
                ('teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='subjects.teachersubject')),
                ('term_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='schools.termyearlevel')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='evaluation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='grades.evaluation'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('evaluation', 'student')},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='coefficient',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='name',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='term_year',
        ),
    ]
