# Generated by Django 4.2.23 on 2025-09-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appreciation',
            name='content',
            field=models.TextField(default='Aucune apréciation.'),
        ),
    ]
