# Generated by Django 4.2.23 on 2025-09-04 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_termyearlevel_remove_termyear_term_and_more'),
        ('grades', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreciation',
            name='term_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations', to='schools.termyearlevel'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='term_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='schools.termyearlevel'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='term_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='schools.termyearlevel'),
        ),
    ]
