# Generated by Django 4.2.23 on 2025-11-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_initial'),
        ('users', '0001_initial'),
        ('schools', '0002_initial'),
        ('grades', '0006_evaluation_max_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreciation',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mention',
            name='mention_type',
            field=models.CharField(choices=[('AB', 'Assez Bien'), ('B', 'Bien'), ('TB', 'Très Bien'), ('EX', 'Excellent'), ('FE', 'Félicitations'), ('EN', 'Encouragements'), ('AV', 'Avertissement Travail'), ('AC', 'Avertissement Conduite')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='appreciation',
            unique_together={('student', 'term_year', 'teacher_subject')},
        ),
    ]
