# Generated by Django 4.2.23 on 2025-08-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(max_length=255, upload_to='documents/staff/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('type_document', models.CharField(choices=[('SCHOOL REPORT', 'school report'), ('ADMINISTRATIVE', 'administrative')], max_length=40)),
                ('document', models.FileField(max_length=255, upload_to='documents/student/')),
            ],
        ),
    ]
