# Generated by Django 4.2.27 on 2025-12-28 13:18

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/youcef/Documents/Bilal/informatique/ProjectSchool/private_files'), upload_to='report_cards/%Y/%m/')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bulletin Scolaire',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du document')),
                ('category', models.CharField(choices=[('ADMIN', 'Administratif'), ('CERTIFICATE', 'Certificat de scolarité'), ('SANCTION', 'Sanction / Discipline'), ('MEDICAL', 'Médical'), ('OTHER', 'Autre')], default='ADMIN', max_length=20)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/youcef/Documents/Bilal/informatique/ProjectSchool/private_files'), upload_to='student_documents/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Élève',
                'ordering': ['-created_at'],
            },
        ),
    ]
