# Generated by Django 4.2.23 on 2025-09-08 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='super_administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='users.superadministrator'),
        ),
        migrations.AddField(
            model_name='exceptiontime',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_times', to='schools.year'),
        ),
        migrations.AddField(
            model_name='exceptionday',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_days', to='schools.year'),
        ),
    ]
