# Generated by Django 4.2.23 on 2025-12-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='schools/logos/', verbose_name="Logo de l'école"),
        ),
        migrations.AddField(
            model_name='school',
            name='primary_color',
            field=models.CharField(default='#374151', help_text='Code couleur hexadécimal pour le bulletin (ex: #2563EB)', max_length=7, verbose_name='Couleur principale (Hex)'),
        ),
        migrations.AddField(
            model_name='school',
            name='principal_signature',
            field=models.ImageField(blank=True, null=True, upload_to='schools/signatures/', verbose_name='Signature du Proviseur (Image)'),
        ),
    ]
