# Generated by Django 4.2.23 on 2025-09-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('HIGHSCHOOL', 'high_school'), ('COLLEGE', 'college')], max_length=50),
        ),
        migrations.DeleteModel(
            name='TypeSchool',
        ),
    ]
