# Generated by Django 4.2.23 on 2025-09-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='term_type',
            field=models.CharField(choices=[('TRIMESTRE', 'Trimestre'), ('SEMESTRE', 'Semestre')], default='TRIMESTRE', max_length=10),
        ),
        migrations.AlterField(
            model_name='exceptionday',
            name='type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='termtype',
            name='type',
            field=models.CharField(choices=[('TRIMESTRE', 'Trimestre'), ('SEMESTRE', 'Semestre')], max_length=10),
        ),
        migrations.AlterField(
            model_name='termyear',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='termyear',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='creation',
            field=models.BooleanField(default=True),
        ),
    ]
