# Generated by Django 4.2.27 on 2026-07-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('HIGHSCHOOL', 'high_school'), ('COLLEGE', 'college'), ('UNIVERSITY', 'university'), ('SCHOOL', 'school')], max_length=50),
        ),
    ]
