# Generated by Django 4.2.23 on 2025-09-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_year_term_type_alter_exceptionday_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermYearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='termyear',
            name='term',
        ),
        migrations.RemoveField(
            model_name='termyear',
            name='year',
        ),
        migrations.RemoveField(
            model_name='year',
            name='term_type',
        ),
        migrations.DeleteModel(
            name='TermType',
        ),
    ]
