# Generated by Django 4.2.27 on 2026-07-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'العربية')], default='fr', max_length=10, verbose_name="Langue de l'école"),
        ),
    ]
