# Generated by Django 4.2.23 on 2025-09-04 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_termyearlevel_remove_termyear_term_and_more'),
        ('grades', '0003_alter_appreciation_term_year_alter_grade_term_year_and_more'),
        ('classes', '0005_level_term_type'),
        ('attendance', '0004_alter_attendance_term_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TermYear',
        ),
        migrations.AddField(
            model_name='termyearlevel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_levels', to='classes.level'),
        ),
        migrations.AddField(
            model_name='termyearlevel',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_years', to='schools.year'),
        ),
    ]
