# Generated by Django 4.2.27 on 2026-07-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'Arabe')], default='fr', max_length=10, verbose_name="Langue de l'école"),
        ),
    ]
