# Generated by Django 4.2.23 on 2025-09-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DELAY', 'delay'), ('ABSENCE', 'absence')], max_length=40)),
                ('justified', models.BooleanField(default=True)),
            ],
        ),
    ]
