# Generated by Django 4.2.27 on 2025-12-28 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_initial'),
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='users.staff'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='term_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='schools.termyearlevel'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.attendancesession'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('session', 'student')},
        ),
    ]
