# Generated by Django 4.2.23 on 2025-09-08 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('attendance', '0002_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='users.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='term_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_year_attendance', to='schools.termyearlevel'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'course')},
        ),
    ]
