# Generated by Django 4.2.23 on 2025-09-04 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_termyearlevel_remove_termyear_term_and_more'),
        ('attendance', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='term_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_year_attendance', to='schools.termyearlevel'),
        ),
    ]
